package org.itson.presentation.standby;

import java.net.Socket;
import java.util.HashMap;
import java.util.Map;
import lombok.Setter;
import org.itson.peertopeer.model.BattleshipPeerMessage;

public class StandbyView extends javax.swing.JFrame {

    private static StandbyView instance;
    
    /**
     * Creates new form StandbyView
     */
    public StandbyView() {
        initComponents();
    }
    
    public static StandbyView getInstance() {
        if (StandbyView.instance == null) {
            StandbyView.instance = new StandbyView();
        }
        return instance;
    }
    
    public void showStandbyScreen() {
        this.setVisible(true);
    }
    
    public void update(Object object) {
        if (object instanceof HashMap message) {
            if (message != null && message.containsKey("host")) {
                this.lblHostValue.setText(message.get("host").toString());
            }
            if (message != null && message.containsKey("port")) {
                this.lblPortValue.setText(message.get("port").toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWaitingPlayer = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblHostValue = new javax.swing.JLabel();
        lblPortValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Standby");
        setResizable(false);

        lblWaitingPlayer.setText("Waiting player...");

        lblHost.setText("Host:");

        lblPort.setText("Port:");

        btnCancel.setText("Cancel");

        lblHostValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblPortValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPortValue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHostValue))
                    .addComponent(lblWaitingPlayer)
                    .addComponent(btnCancel))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWaitingPlayer)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHost)
                    .addComponent(lblHostValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(lblPortValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblHostValue;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblPortValue;
    private javax.swing.JLabel lblWaitingPlayer;
    // End of variables declaration//GEN-END:variables
}
